### ISSUE TITLE
istiod issue

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/dce-charts-repackage#1085]
https://github.com/DaoCloud/dce-charts-repackage/actions/runs/5072952618

```
error, failed to check image 127.0.0.1:30080/pilot:1.17.1 from chart template for istiod, because the image does not have repository
```

参考修复 https://github.com/DaoCloud/dce-charts-repackage/pull/1080

**Comment by weizhoublue** [comment]
to 
nicole-lihui

**Comment by nicole-lihui** [comment]
我在修复过程中，发现 istio 没法适配 image： 带 / 的格式， 
因为它的原则是，如果带了 / 则认为是一个完整的镜像，将会不会按多层模版渲染：
定义如下： 
https://github.com/DaoCloud/dce-charts-repackage/blob/main/charts/istiod/istiod/charts/istiod/templates/deployment.yaml#L80-L84

我的想法是如果按照 这个规范的话，是不是成本太大了，我需要将所有 istio 相关的镜像渲染替换，感觉成本有点高，后续并不好维护。

@weizhoublue @kebe7jun

**Comment by weizhoublue** [comment]
需要和 @learner0810  讨论下 解决方案，是否影响 私有化环境 部署
