### ISSUE TITLE
robot: test new version falco-event-generator 0.1.1 by PR 428

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/dce-charts-repackage#429]
I am robot, Trigger by PR <https://github.com/DaoCloud/dce-charts-repackage/pull/428>, charts falco-event-generator 0.1.1 has been released with new version to daocloud chart registery. Refer to Github Action <https://github.com/DaoCloud/dce-charts-repackage/actions/runs/3786574651>

**Comment by ty-dc** [comment]
# falco-event-generator 0.1.1 在arm与x86 集群上正常运行
## arm
<img width="863" alt="image" src="https://user-images.githubusercontent.com/101157744/210750767-043e6f00-9342-49a8-875f-c1ab232f5f6d.png">
## x86:
<img width="893" alt="image" src="https://user-images.githubusercontent.com/101157744/210751512-f658c9b0-bcc3-4910-bb14-745da74f7313.png">
