### ISSUE TITLE
robot: test new version kube-bench 0.1.5 by PR 536

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/dce-charts-repackage#548]
I am robot, Trigger by PR <https://github.com/DaoCloud/dce-charts-repackage/pull/536>, charts kube-bench 0.1.5 has been released with new version to daocloud chart registery. Refer to Github Action <https://github.com/DaoCloud/dce-charts-repackage/actions/runs/4084190269>

**Comment by ty-dc** [comment]
kube-bench 0.1.5 可以安装成功。
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/101157744/224946673-fd6bb1c5-5282-458d-b77e-374d38971f30.png">

安装界面缺少各参数名词的解释和如何填写的提示。
<img width="942" alt="image" src="https://user-images.githubusercontent.com/101157744/224947051-45e321d0-c6dd-48b4-a8a0-5c5604983cbd.png">

**Comment by weizhoublue** [comment]
closed by CI <https://github.com/DaoCloud/dce-charts-repackage/actions/runs/5110043550>
