### ISSUE TITLE
robot: test new version neuvector 2.4.2 by PR 617

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/dce-charts-repackage#624]
I am robot, Trigger by PR <https://github.com/DaoCloud/dce-charts-repackage/pull/617>, charts neuvector 2.4.2 has been released with new version to daocloud chart registery. Refer to Github Action <https://github.com/DaoCloud/dce-charts-repackage/actions/runs/4180331926>

**Comment by ty-dc** [comment]
global registry：应该有个默认值或则对如何填写有一定说明。

<img width="1052" alt="image" src="https://user-images.githubusercontent.com/101157744/224955494-675b22de-46ff-4034-bf55-37eff8b9c7da.png">

其次对必填项或则非必填项，做一下校验。否则一旦未填，将无法创建。
```
helm install --create-namespace=true --namespace=kube-system --values=/home/shell/helm/values-neuvector-2.4.2.yaml --version=2.4.2 neuvector /home/shell/helm/neuvector-2.4.2.tgz
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /home/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /home/.kube/config
Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
neuvector:
- core.controller.pvc.storageClass: Invalid type. Expected: string, given: null
- core.controller.pvc.capacity: Invalid type. Expected: string, given: null
```

**Comment by weizhoublue** [comment]
closed by CI <https://github.com/DaoCloud/dce-charts-repackage/actions/runs/5110043550>
