### ISSUE TITLE
robot: test new version kuberhealthy 90 by PR 633

### ISSUE THREAD

**Issue by weizhoublue** [DaoCloud/dce-charts-repackage#667]
I am robot, Trigger by PR <https://github.com/DaoCloud/dce-charts-repackage/pull/633>, charts kuberhealthy 90 has been released with new version to daocloud chart registery. Refer to Github Action <https://github.com/DaoCloud/dce-charts-repackage/actions/runs/4201420196>

**Comment by ty-dc** [comment]
The same bug as: #703
